import { CloudService } from "../types";

export const RECOMMENDED_CLOUD_SERVICES_MATRIX: Record<string, CloudService> = {
  Authentication: {
    id: "cloud-auth",
    name: "Supabase Auth",
    serviceType: "Authentication",
    provider: "Supabase Inc.",
    purpose: "OAuth 2.0 PKCE, Magic Links, MFA, and JWT session management.",
    whyChosen: "Turnkey integration with React Native Expo SecureStore, official Supabase JS SDK, Row Level Security (RLS) policies, and multi-provider social logins.",
    pricing: "Free Tier: 50,000 monthly active users (MAU); Pro Plan: $25/mo for 100,000 MAU.",
    expoCompatibility: "Native JS SDK (Zero native build steps, works in Expo Go & Dev Client).",
    easeOfSetup: "Trivial",
    productionSuitability: "Enterprise Grade (SOC2 Type II certified, PostgreSQL RLS backed).",
    alternatives: ["Clerk", "Firebase Auth", "Auth0"],
    environmentVariableKeys: ["EXPO_PUBLIC_SUPABASE_URL", "EXPO_PUBLIC_SUPABASE_ANON_KEY"],
    docUrl: "https://supabase.com/docs/guides/auth"
  },
  Database: {
    id: "cloud-db",
    name: "Supabase Postgres",
    serviceType: "Database",
    provider: "Supabase / AWS RDS",
    purpose: "Relational database, vector search (pgvector), and auto-generated REST/GraphQL APIs.",
    whyChosen: "Full PostgreSQL engine with instant Row Level Security, pgvector for AI embeddings, automated daily backups, and instant connection pooling.",
    pricing: "Free Tier: 500 MB database & 5 GB storage; Pro Plan: $25/mo for 8 GB database.",
    expoCompatibility: "Native JS SDK & Direct HTTP API (Fully compatible with universal Expo apps).",
    easeOfSetup: "Trivial",
    productionSuitability: "High Velocity Scale (Handles millions of queries with PgBouncer connection pooler).",
    alternatives: ["Convex", "PlanetScale", "Neon Postgres"],
    environmentVariableKeys: ["EXPO_PUBLIC_SUPABASE_URL", "EXPO_PUBLIC_SUPABASE_ANON_KEY"],
    docUrl: "https://supabase.com/docs/guides/database"
  },
  Storage: {
    id: "cloud-storage",
    name: "Cloudflare R2",
    serviceType: "Storage",
    provider: "Cloudflare Inc.",
    purpose: "S3-compatible object storage for photos, videos, and user uploads with zero egress fees.",
    whyChosen: "Eliminates egress bandwidth costs completely, AWS S3 API compatible, global CDN integration, and pre-signed upload URLs.",
    pricing: "Free Tier: 10 GB storage & 10 Million read requests/mo; Pay-as-you-go: $0.015/GB/mo with $0 egress.",
    expoCompatibility: "HTTP REST API & AWS S3 Client SDK (Pre-signed direct client upload compatible).",
    easeOfSetup: "Moderate",
    productionSuitability: "Enterprise Grade (Global edge network with sub-50ms latency globally).",
    alternatives: ["AWS S3", "Supabase Storage", "Firebase Storage"],
    environmentVariableKeys: ["EXPO_PUBLIC_STORAGE_BUCKET_URL"],
    docUrl: "https://developers.cloudflare.com/r2/"
  },
  Payments: {
    id: "cloud-payments",
    name: "Stripe Connect & RevenueCat",
    serviceType: "Payments",
    provider: "Stripe Inc. / RevenueCat Inc.",
    purpose: "PCI-compliant payment processing, Apple/Google In-App Purchase subscriptions, and seller payouts.",
    whyChosen: "Stripe provides PCI-compliant Payment Sheets; RevenueCat abstracts App Store and Google Play subscription validation & webhooks.",
    pricing: "Stripe: 2.9% + 30¢ per transaction; RevenueCat: Free up to $2,500 MTR (Monthly Tracked Revenue).",
    expoCompatibility: "Native Expo Config Plugins (@stripe/stripe-react-native & react-native-purchases).",
    easeOfSetup: "Moderate",
    productionSuitability: "Enterprise Grade (Global payment compliance, multi-currency, tax calculation).",
    alternatives: ["Lemon Squeezy", "Paddle", "PayPal"],
    environmentVariableKeys: ["EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
    docUrl: "https://stripe.com/docs/stripe-react-native"
  },
  Notifications: {
    id: "cloud-notifications",
    name: "Expo Push Service & OneSignal",
    serviceType: "Notifications",
    provider: "Expo / OneSignal Inc.",
    purpose: "Cross-platform APNs (Apple) & FCM (Google) push token registration and broadcast notifications.",
    whyChosen: "Expo Push handles push token resolution without manual Apple APNs/Google FCM setup in development; OneSignal scales for segment marketing.",
    pricing: "Expo Push: 100% Free; OneSignal: Free up to 10,000 subscribers.",
    expoCompatibility: "Native SDK (expo-notifications & onesignal-expo-plugin).",
    easeOfSetup: "Trivial",
    productionSuitability: "High Velocity Scale (Delivers millions of push alerts with sub-second concurrency).",
    alternatives: ["Firebase Cloud Messaging (FCM direct)", "Braze"],
    environmentVariableKeys: ["EXPO_PUBLIC_ONESIGNAL_APP_ID"],
    docUrl: "https://docs.expo.dev/push-notifications/overview/"
  },
  Analytics: {
    id: "cloud-analytics",
    name: "PostHog Analytics",
    serviceType: "Analytics",
    provider: "PostHog Inc.",
    purpose: "Product analytics, event tracking, screen path recording, and user retention funnels.",
    whyChosen: "Open-source product analytics platform with mobile session replay, screen path tracking, privacy compliance, and self-hosting options.",
    pricing: "Free Tier: 1 Million events/mo & 5,000 session replays/mo; Pay-as-you-go thereafter.",
    expoCompatibility: "Native JS SDK (posthog-react-native with Expo Router integration).",
    easeOfSetup: "Trivial",
    productionSuitability: "Enterprise Grade (SOC2 Type II, GDPR compliant, self-hostable).",
    alternatives: ["Mixpanel", "Amplitude", "Google Analytics"],
    environmentVariableKeys: ["EXPO_PUBLIC_POSTHOG_API_KEY", "EXPO_PUBLIC_POSTHOG_HOST"],
    docUrl: "https://posthog.com/docs/libraries/react-native"
  },
  CrashReporting: {
    id: "cloud-crash",
    name: "Sentry Error Tracking",
    serviceType: "Crash Reporting",
    provider: "Functional Software Inc. (Sentry)",
    purpose: "Real-time JavaScript error tracking, native iOS/Android crash symbolication, and release health metrics.",
    whyChosen: "Automated Expo source-map symbolication, native C++/Swift stack trace capture, breadcrumbs, and performance transaction traces.",
    pricing: "Free Developer Tier: 5,000 errors/mo; Team Plan: $26/mo for 50,000 errors.",
    expoCompatibility: "Official Expo Config Plugin (@sentry/react-native).",
    easeOfSetup: "Trivial",
    productionSuitability: "Enterprise Grade (De-facto industry standard for mobile observability).",
    alternatives: ["Bugsnag", "Firebase Crashlytics"],
    environmentVariableKeys: ["EXPO_PUBLIC_SENTRY_DSN"],
    docUrl: "https://docs.sentry.io/platforms/react-native/manual-setup/expo/"
  },
  FeatureFlags: {
    id: "cloud-ff",
    name: "PostHog Feature Flags",
    serviceType: "Feature Flags",
    provider: "PostHog Inc.",
    purpose: "Dynamic feature toggles, A/B experimentation, and gradual rollout management without App Store resubmissions.",
    whyChosen: "Bundled directly into PostHog React Native SDK; evaluate flags locally with zero network latency, fallback defaults, and user cohorts.",
    pricing: "Free Tier: 1 Million flag requests/mo included in free plan.",
    expoCompatibility: "Native JS SDK (Instant flag evaluation).",
    easeOfSetup: "Trivial",
    productionSuitability: "High Velocity Scale (Local cache evaluation prevents UI thread blocking).",
    alternatives: ["LaunchDarkly", "Statsig", "Flagsmith"],
    environmentVariableKeys: ["EXPO_PUBLIC_POSTHOG_API_KEY"],
    docUrl: "https://posthog.com/docs/feature-flags"
  },
  Monitoring: {
    id: "cloud-monitoring",
    name: "Datadog / Axiom Observability",
    serviceType: "Monitoring",
    provider: "Datadog Inc. / Axiom Inc.",
    purpose: "Real-user monitoring (RUM), network request latency timing, and serverless edge log aggregation.",
    whyChosen: "Tracks mobile client HTTP request latency, screen rendering performance, and serverless backend API health in a single dashboard.",
    pricing: "Axiom: Free Tier up to 50 GB ingestion/mo; Datadog: $15/host/mo.",
    expoCompatibility: "Native JS Client SDK (@datadog/mobile-react-native).",
    easeOfSetup: "Moderate",
    productionSuitability: "Enterprise Grade (Full SOC2 Type II compliance with multi-region ingestion).",
    alternatives: ["Grafana Loki", "LogRocket", "New Relic"],
    environmentVariableKeys: ["EXPO_PUBLIC_DATADOG_CLIENT_TOKEN"],
    docUrl: "https://docs.datadoghq.com/real_user_monitoring/reactnative/"
  },
  Search: {
    id: "cloud-search",
    name: "Algolia InstantSearch",
    serviceType: "Search",
    provider: "Algolia Inc.",
    purpose: "Sub-50ms typo-tolerant multi-facet search index and recommendation discovery.",
    whyChosen: "Industry standard for fast mobile search with typo tolerance, instant filtering, geo-search bounds, and native React Native widgets.",
    pricing: "Free Build Tier: 10,000 search requests/mo; Grow Tier: $1.00 per 1,000 search requests.",
    expoCompatibility: "Native JS SDK (algoliasearch & react-instantsearch-core).",
    easeOfSetup: "Moderate",
    productionSuitability: "Enterprise Grade (Global search index CDN clusters with sub-20ms SLA).",
    alternatives: ["Meilisearch", "Typesense", "Elasticsearch"],
    environmentVariableKeys: ["EXPO_PUBLIC_ALGOLIA_APP_ID", "EXPO_PUBLIC_ALGOLIA_SEARCH_KEY"],
    docUrl: "https://www.algolia.com/doc/guides/building-search-ui/getting-started/react-native/"
  },
  Realtime: {
    id: "cloud-realtime",
    name: "Supabase Realtime / Ably",
    serviceType: "Realtime",
    provider: "Supabase / Ably Inc.",
    purpose: "WebSocket channels for live chat messages, driver GPS coordinates, presence status, and broadcast signals.",
    whyChosen: "Listens directly to Postgres database changes via WebSockets, handles reconnect backoff, presence state, and broadcast message channels.",
    pricing: "Supabase Realtime: Included in Supabase free tier (up to 200 concurrent connections).",
    expoCompatibility: "Native WebSockets (Standard React Native WebSocket implementation).",
    easeOfSetup: "Trivial",
    productionSuitability: "High Velocity Scale (Scales to tens of thousands of concurrent WebSocket connections).",
    alternatives: ["Pusher", "Socket.io", "AWS AppSync"],
    environmentVariableKeys: ["EXPO_PUBLIC_SUPABASE_URL"],
    docUrl: "https://supabase.com/docs/guides/realtime"
  },
  Maps: {
    id: "cloud-maps",
    name: "Google Maps Platform & Mapbox",
    serviceType: "Maps",
    provider: "Google LLC / Mapbox Inc.",
    purpose: "Vector map tiles, address geocoding, autocomplete search, and turn-by-turn route directions.",
    whyChosen: "Google Maps provides standard native map rendering on Android & iOS; Mapbox provides custom styled vector maps and cluster markers.",
    pricing: "Google Maps: $200 free monthly credit (~28,500 map loads); Mapbox: 50,000 free monthly map loads.",
    expoCompatibility: "Native Config Plugins (react-native-maps & @rnmapbox/maps).",
    easeOfSetup: "Moderate",
    productionSuitability: "Enterprise Grade (99.99% uptime global map tile delivery).",
    alternatives: ["Radar.io", "Here Maps", "Apple Maps"],
    environmentVariableKeys: ["EXPO_PUBLIC_GOOGLE_MAPS_API_KEY"],
    docUrl: "https://developers.google.com/maps/documentation/android-sdk/overview"
  },
  AI: {
    id: "cloud-ai",
    name: "Groq Cloud API & OpenAI API",
    serviceType: "AI",
    provider: "Groq Inc. / OpenAI LLC",
    purpose: "Ultra-low-latency LLM inference (Llama 3.3 70B, GPT-4o), vision multi-modal processing, and embeddings.",
    whyChosen: "Groq LPUs deliver 500+ tokens/sec for sub-second AI assistant completions; OpenAI handles multimodal vision & embeddings.",
    pricing: "Groq: Free developer rate limits; OpenAI: Pay-as-you-go per 1M tokens ($0.15/1M input).",
    expoCompatibility: "HTTP Streaming SSE / REST API (Native fetch & EventSource compatible).",
    easeOfSetup: "Trivial",
    productionSuitability: "High Velocity Scale (Sub-second latency inference suitable for real-time mobile UX).",
    alternatives: ["Anthropic Claude", "Replicate", "Together AI"],
    environmentVariableKeys: ["EXPO_PUBLIC_GROQ_API_KEY"],
    docUrl: "https://console.groq.com/docs/quickstart"
  },
  Email: {
    id: "cloud-email",
    name: "Resend / Postmark",
    serviceType: "Email",
    provider: "Resend Inc. / Wildbit (Postmark)",
    purpose: "Transactional email delivery for welcome emails, order receipts, password resets, and magic link auth.",
    whyChosen: "Modern developer-first API, React Email component support, sub-second transactional delivery rates, and high inbox deliverability.",
    pricing: "Resend Free Tier: 3,000 emails/month (100 emails/day); Pro: $20/month for 50,000 emails.",
    expoCompatibility: "HTTP REST API (Serverless backend API call compatible).",
    easeOfSetup: "Trivial",
    productionSuitability: "Enterprise Grade (99.9% inbox deliverability reputation).",
    alternatives: ["SendGrid", "AWS SES", "Mailgun"],
    environmentVariableKeys: ["RESEND_API_KEY"],
    docUrl: "https://resend.com/docs/introduction"
  }
};
